title: Claire-Emeraude Filtz
position: Masterâ€™s Student - M.A. Linguistics
affiliation: Leiden University, Netherlands
email: claireemeraude.filtz@gmail.com
keywords: Linguistics Semantics Pragmatics
github_link: https://github.com/clairefiltz
avatar: ./assets/img/profile.png
description: Personal home page.
canonical: https://clairefiltz.github.io/
remote_theme: yaoyao-liu/minimal-light
